/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

import {LitElement, html} from 'lit';
import {customElement} from 'lit/decorators.js';
import sheet from './hmr-vsheet.css?css-sheet';

/**
 * Adopts a shared hot-swapping `CSSStyleSheet` via the plugin's `?css-sheet`
 * query — the whole `urlSheet()` + `import.meta.hot.accept` wiring is
 * generated by the plugin, so this module is just a bare import. Editing
 * `hmr-vsheet.css` restyles this and `hmr-vsheet-b` in place, no re-render.
 *
 * Tradeoffs — same fetched-shared-sheet profile as `hmr-utility-sheet`
 * (recommended for a shared utility layer: one sheet, cacheable `.css` asset,
 * in-place HMR; brief FOUC/CLS on first load), but with zero boilerplate. ❌
 * Only works through this plugin — `urlSheet()` is the portable form. See
 * ../../docs/css-delivery.md (benchmarked in bench/).
 */

@customElement('hmr-vsheet-a')
export class HmrVsheetA extends LitElement {
  static override styles = [sheet];

  private renders = 0;

  override render() {
    return html`<span class="chip" id="chip">A</span>
      <span id="badge">renders: 0</span>`;
  }

  override updated() {
    this.renders++;
    this.setAttribute('data-renders', String(this.renders));
    const badge = this.renderRoot.querySelector('#badge');
    if (badge !== null) {
      badge.textContent = `renders: ${this.renders}`;
    }
  }
}
